DROP TABLE IF EXISTS Trade;
CREATE TABLE IF NOT EXISTS Trade (
  Name CHAR(20) PRIMARY KEY NOT NULL UNIQUE
);

DROP TABLE IF EXISTS WorkMethod;
CREATE TABLE IF NOT EXISTS WorkMethod (
  TradeName CHAR(20) REFERENCES Trade (Name) ON DELETE CASCADE,
  Method CHAR(50) PRIMARY KEY NOT NULL UNIQUE,
  Productivity REAL NOT NULL
);

DROP TABLE IF EXISTS WorkMethodDependency;
CREATE TABLE IF NOT EXISTS WorkMethodDependency (
  Predecessor CHAR(50) REFERENCES WorkMethod (Method) ON DELETE CASCADE,
  Successor CHAR(50) REFERENCES WorkMethod (Method) ON DELETE CASCADE,
  PRIMARY KEY (Predecessor, Successor)
);

DROP TABLE IF EXISTS Space;
CREATE TABLE IF NOT EXISTS Space (
  Name CHAR(30) PRIMARY KEY NOT NULL UNIQUE
);

DROP TABLE IF EXISTS Design;
CREATE TABLE IF NOT EXISTS Design (
  WorkMethod CHAR(50) REFERENCES WorkMethod (Method) ON DELETE CASCADE,
  Space CHAR(30) REFERENCES Space (Name) ON DELETE CASCADE,
  Quantity REAL NOT NULL ,
  PRIMARY KEY (WorkMethod, Space)
);

DROP TABLE IF EXISTS Workflow;
CREATE TABLE IF NOT EXISTS Workflow (
  WorkMethod CHAR(50) REFERENCES WorkMethod (Method) ON DELETE CASCADE,
  Space CHAR(30) REFERENCES Space (Name) ON DELETE CASCADE,
  Quantity REAL NOT NULL ,
  PRIMARY KEY (WorkMethod, Space)
);
